<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'AppBundle\Controller\Admin\AdminController' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerAwareTrait.php';
include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Controller/ControllerTrait.php';
include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Controller/Controller.php';
include_once $this->targetDirs[3].'/src/AppBundle/Controller/Admin/AdminController.php';

return $this->services['AppBundle\Controller\Admin\AdminController'] = new \AppBundle\Controller\Admin\AdminController(${($_ = isset($this->services['AppBundle\Service\Blog\PostService']) ? $this->services['AppBundle\Service\Blog\PostService'] : $this->load(__DIR__.'/getPostServiceService.php')) && false ?: '_'}, ${($_ = isset($this->services['AppBundle\Service\Blog\CategoryService']) ? $this->services['AppBundle\Service\Blog\CategoryService'] : $this->load(__DIR__.'/getCategoryServiceService.php')) && false ?: '_'});
