<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'AppBundle\Service\Blog\PostService' shared autowired service.

include_once $this->targetDirs[3].'/src/AppBundle/Service/Blog/PostService.php';

return $this->services['AppBundle\Service\Blog\PostService'] = new \AppBundle\Service\Blog\PostService(${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->load(__DIR__.'/getDoctrine_Orm_DefaultEntityManagerService.php')) && false ?: '_'});
